/*
 * SPDX-FileCopyrightText: 2021-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Unlicense OR CC0-1.0
 */
#define TAG "SMYTH"

#include <stdint.h>
#include <math.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_pdm.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_check.h"
#include "sdkconfig.h"
#include "i2s_pdm_example.h"
#include "i2s_example_pins.h"
#include "esp_littlefs.h"
#include "dirent.h"
#include <string.h>
#include "format_wav.h"


#define EXAMPLE_PDM_TX_CLK_IO           EXAMPLE_I2S_BCLK_IO1      // I2S PDM TX clock io number
#define EXAMPLE_PDM_TX_DOUT_IO          EXAMPLE_I2S_DOUT_IO1      // I2S PDM TX data out io number

#define EXAMPLE_PDM_TX_FREQ_HZ          16000           // I2S PDM TX frequency
#define EXAMPLE_WAVE_AMPLITUDE          (1000.0)        // 1~32767
#define CONST_PI                        (3.1416f)
#define EXAMPLE_SINE_WAVE_LEN(tone)     (uint32_t)((EXAMPLE_PDM_TX_FREQ_HZ / (float)tone) + 0.5) // The sample point number per sine wave to generate the tone
#define EXAMPLE_TONE_LAST_TIME_MS       500
#define EXAMPLE_BYTE_NUM_EVERY_TONE     (EXAMPLE_TONE_LAST_TIME_MS * EXAMPLE_PDM_TX_FREQ_HZ / 1000)

// Handles
i2s_chan_handle_t tx_handle;

/* The frequency of tones: do, re, mi, fa, so, la, si, in Hz. */
static const uint32_t tone[3][7] = {
    {262, 294, 330, 349, 392, 440, 494},        // bass
    {523, 587, 659, 698, 784, 880, 988},        // alto
    {1046, 1175, 1318, 1397, 1568, 1760, 1976}, // treble
};
/* Numbered musical notation of 'twinkle twinkle little star' */
static const uint8_t song[28] = {1, 1, 5, 5, 6, 6, 5,
                                 4, 4, 3, 3, 2, 2, 1,
                                 5, 5, 4, 4, 3, 3, 2,
                                 5, 5, 4, 4, 3, 3, 2
                                };
/* Rhythm of 'twinkle twinkle little star', it's repeated in four sections */
static const uint8_t rhythm[7] = {1, 1, 1, 1, 1, 1, 2};

static const char *tone_name[3] = {"bass", "alto", "treble"};

static i2s_chan_handle_t i2s_example_init_pdm_tx(void)
{
    i2s_chan_handle_t tx_chan;        // I2S tx channel handler
    /* Setp 1: Determine the I2S channel configuration and allocate TX channel only
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role,
     * but note that PDM channel can only be registered on I2S_NUM_0 */
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    tx_chan_cfg.auto_clear = true;
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

    /* Step 2: Setting the configurations of PDM TX mode and initialize the TX channel
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_pdm.h' which can only be used in PDM TX mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_pdm_tx_config_t pdm_tx_cfg = {
#if CONFIG_EXAMPLE_PDM_TX_DAC
        .clk_cfg = I2S_PDM_TX_CLK_DAC_DEFAULT_CONFIG(EXAMPLE_PDM_TX_FREQ_HZ),
        /* The data bit-width of PDM mode is fixed to 16 */
        .slot_cfg = I2S_PDM_TX_SLOT_DAC_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_MONO),
#else
        .clk_cfg = I2S_PDM_TX_CLK_DEFAULT_CONFIG(48000),
        /* The data bit-width of PDM mode is fixed to 24 */
        .slot_cfg = I2S_PDM_TX_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_24BIT, I2S_SLOT_MODE_MONO),
#endif
        .gpio_cfg = {
            .clk = EXAMPLE_PDM_TX_CLK_IO,
            .dout = EXAMPLE_PDM_TX_DOUT_IO,
            .invert_flags = {
                .clk_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_pdm_tx_mode(tx_chan, &pdm_tx_cfg));

    /* Step 3: Enable the tx channel before writing data */
    ESP_ERROR_CHECK(i2s_channel_enable(tx_chan));

    return tx_chan;
}

static esp_err_t i2s_init_std_mode(void)
{
    i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    tx_chan_cfg.auto_clear = true;
    ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_handle, NULL));

    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(44100),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = GPIO_NUM_4,
            .ws = GPIO_NUM_5,
            .dout = GPIO_NUM_2 ,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    return i2s_channel_init_std_mode(tx_handle, &std_cfg);
}


void i2s_example_pdm_tx_task(void *args)
{
    int16_t *w_buf = (int16_t *)calloc(1, EXAMPLE_BUFF_SIZE);
    assert(w_buf);
    i2s_chan_handle_t tx_chan = i2s_example_init_pdm_tx();

    size_t w_bytes = 0;

    uint8_t cnt = 0;            // The current index of the song
    uint8_t tone_select = 0;    // To selecting the tone level

    printf("Playing %s `twinkle twinkle little star`\n", tone_name[tone_select]);
    while (1) {
        int tone_point = EXAMPLE_SINE_WAVE_LEN(tone[tone_select][song[cnt] - 1]);
        /* Generate the tone buffer */
        for (int i = 0; i < tone_point; i++) {
            w_buf[i] = (int16_t)((sin(2 * (float)i * CONST_PI / tone_point)) * EXAMPLE_WAVE_AMPLITUDE);
            printf("%d\n", w_buf[i]);
        }
        for (int tot_bytes = 0; tot_bytes < EXAMPLE_BYTE_NUM_EVERY_TONE * rhythm[cnt % 7]; tot_bytes += w_bytes) {
            /* Play the tone */
            if (i2s_channel_write(tx_chan, w_buf, tone_point * sizeof(int16_t), &w_bytes, 1000) != ESP_OK) {
                printf("Write Task: i2s write failed\n");
            }
        }
        cnt++;
        /* If finished playing, switch the tone level */
        if (cnt == sizeof(song)) {
            cnt = 0;
            tone_select++;
            tone_select %= 3;
            printf("Playing %s `twinkle twinkle little star`\n", tone_name[tone_select]);
        }
        /* Gap between the tones */
        vTaskDelay(15);
    }
    free(w_buf);
    vTaskDelete(NULL);
}

void list_files(const char *path) {
    printf("Opening directory: %s\n", path);
    DIR *dir = opendir(path);
    if (dir == NULL) {
        printf("Failed to open directory: %s\n", path);
        return;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL) {
        printf("Found file: %s\n", entry->d_name);
    }

    closedir(dir);
}

typedef struct {
    wav_header_t wav_header;
    int16_t *data;
} wav_file_t;

wav_file_t read_wav_file(const char *path){
    wav_file_t wav_file = {0};
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        printf("Failed to open file for reading\n");
        return wav_file;
    }
    fread(&wav_file.wav_header, sizeof(wav_header_t), 1, file);

    printf("chunk_id: %s\n", wav_file.wav_header.descriptor_chunk.chunk_id);
    printf("chunk_size: %lu\n", wav_file.wav_header.descriptor_chunk.chunk_size);
    printf("chunk_format: %s\n", wav_file.wav_header.descriptor_chunk.chunk_format);
    printf("subchunk_id: %s\n", wav_file.wav_header.fmt_chunk.subchunk_id);
    printf("subchunk_size: %lu\n", wav_file.wav_header.fmt_chunk.subchunk_size);
    printf("audio_format: %u\n", wav_file.wav_header.fmt_chunk.audio_format);
    printf("num_of_channels: %u\n", wav_file.wav_header.fmt_chunk.num_of_channels);
    printf("sample_rate: %lu\n", wav_file.wav_header.fmt_chunk.sample_rate);
    printf("byte_rate: %lu\n", wav_file.wav_header.fmt_chunk.byte_rate);
    printf("block_align: %u\n", wav_file.wav_header.fmt_chunk.block_align);
    printf("bits_per_sample: %u\n", wav_file.wav_header.fmt_chunk.bits_per_sample);
    printf("subchunk_id: %s\n", wav_file.wav_header.data_chunk.subchunk_id);
    printf("subchunk_size: %lu\n", wav_file.wav_header.data_chunk.subchunk_size);


    wav_file.data = (int16_t *)malloc(wav_file.wav_header.data_chunk.subchunk_size);
    fread(wav_file.data, sizeof(int16_t), wav_file.wav_header.data_chunk.subchunk_size, file);
    printf("Read Data buffer: ");
    for (int i = 0; i < 100; i++) {
        printf("%d ", wav_file.data[i]);
    }
    fclose(file);

    return wav_file;
}

typedef struct {
    i2s_chan_handle_t *tx_chan;
    wav_file_t wav_file;
}i2s_task_params_t;

void i2s_transmit_wav(void *pvParameters){
    // Parameter acquisition
    i2s_task_params_t *params = (i2s_task_params_t *)pvParameters;
    i2s_chan_handle_t *tx_chan = params->tx_chan;
    wav_header_t *wav_header = &params->wav_file.wav_header;
    int16_t *data = params->wav_file.data;

    size_t written_bytes = 0;
    size_t read_bytes = 2048;
    size_t data_size = wav_header->data_chunk.subchunk_size;

    int16_t *buf = calloc(EXAMPLE_BUFF_SIZE, sizeof(int16_t));
    memcpy(buf, data, EXAMPLE_BUFF_SIZE * sizeof(int16_t));
    
    i2s_channel_enable(tx_handle);
    while(1){
        printf("Buffer buffer: ");
        for (int i = 0; i < 10; i++) {
            printf("%d ", buf[i]);
        }
        printf("Data buffer: ");
        for (int i = 0; i < 10; i++) {
            printf("%d ", data[i]);
        }
        printf("\n");
        while(read_bytes > 0){
            printf("I arrived here\n");  
            ESP_ERROR_CHECK(i2s_channel_write(*tx_chan, buf, data_size * sizeof(int16_t), &written_bytes, 1000));
            printf("Read bytes: %zu\n", read_bytes);
            printf("Written bytes: %zu\n", written_bytes);  
            vTaskDelay(150);
        }
        printf("Data bytes: %zu\n", data_size);
        printf("Written bytes: %zu\n", written_bytes);
       
    }
    vTaskDelete(NULL);
} 


void app_main(void)
{
    esp_vfs_littlefs_conf_t conf = {
        .base_path = "/littlefs",
        .partition_label = "littlefs",
        .format_if_mount_failed = true,
        .dont_mount = false,
    };
    esp_err_t ret = esp_vfs_littlefs_register(&conf);

    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Failed to mount or format filesystem");
        } else if (ret == ESP_ERR_NOT_FOUND) {
            ESP_LOGE(TAG, "Failed to find LittleFS partition");
        } else {
            ESP_LOGE(TAG, "Failed to initialize LittleFS (%s)", esp_err_to_name(ret));
        }
        return;
    }
    list_files("/littlefs");

    wav_file_t wav_file = read_wav_file("/littlefs/Kick2.wav");

    FILE *file = fopen("/littlefs/hello.txt", "r");
    if (file == NULL) {
        printf("Failed to open file for reading\n");
        return;
    }

    int16_t *w_buf = (int16_t *)calloc(1, EXAMPLE_BUFF_SIZE);
    assert(w_buf);
    ESP_ERROR_CHECK(i2s_init_std_mode());
    
    i2s_task_params_t params = {
        .tx_chan = &tx_handle,
        .wav_file = wav_file,
    };
    printf("I2S PDM TX example start\n---------------------------\n");

    xTaskCreate(i2s_transmit_wav, "i2s", 4096, (void*) &params, 5, NULL);
    //xTaskCreate(i2s_example_pdm_tx_task, "i2s_example_pdm_tx_task", 4096, NULL, 5, NULL);
}